# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 770217dc43c9c627e59a364307bc02e7577b2e2086dc5a5ee92b97bdcd0bd9586691e5da53781feeef52f19d79ed02b0ab09a55ce76a13ac892d4f4f00050ed6

test:
  secret_key_base: e95efb38ca2f348e51ce4ade210932739346a3b0f34f8cd48d82b8cd11bb0792e56b477cb0bfd79d462fef0f8ebfda993f61f1c5ab208ac22c2c0cc07d245e69

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
